/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LogoutImport } from './routes/logout'
import { Route as AboutImport } from './routes/about'
import { Route as UserImport } from './routes/_user'
import { Route as StoreImport } from './routes/_store'
import { Route as SplitImport } from './routes/_split'
import { Route as IndexImport } from './routes/index'
import { Route as UserHomeImport } from './routes/_user/home'
import { Route as SplitStoreImport } from './routes/_split/store'
import { Route as SplitLoginImport } from './routes/_split/login'
import { Route as StoreStoreSlugIndexImport } from './routes/_store/store/$slug/index'
import { Route as StoreStoreSlugSettingImport } from './routes/_store/store/$slug/setting'

// Create/Update Routes

const LogoutRoute = LogoutImport.update({
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const UserRoute = UserImport.update({
  id: '/_user',
  getParentRoute: () => rootRoute,
} as any)

const StoreRoute = StoreImport.update({
  id: '/_store',
  getParentRoute: () => rootRoute,
} as any)

const SplitRoute = SplitImport.update({
  id: '/_split',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserHomeRoute = UserHomeImport.update({
  path: '/home',
  getParentRoute: () => UserRoute,
} as any)

const SplitStoreRoute = SplitStoreImport.update({
  path: '/store',
  getParentRoute: () => SplitRoute,
} as any)

const SplitLoginRoute = SplitLoginImport.update({
  path: '/login',
  getParentRoute: () => SplitRoute,
} as any)

const StoreStoreSlugIndexRoute = StoreStoreSlugIndexImport.update({
  path: '/store/$slug/',
  getParentRoute: () => StoreRoute,
} as any)

const StoreStoreSlugSettingRoute = StoreStoreSlugSettingImport.update({
  path: '/store/$slug/setting',
  getParentRoute: () => StoreRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_split': {
      id: '/_split'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SplitImport
      parentRoute: typeof rootRoute
    }
    '/_store': {
      id: '/_store'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StoreImport
      parentRoute: typeof rootRoute
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UserImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/_split/login': {
      id: '/_split/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof SplitLoginImport
      parentRoute: typeof SplitImport
    }
    '/_split/store': {
      id: '/_split/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof SplitStoreImport
      parentRoute: typeof SplitImport
    }
    '/_user/home': {
      id: '/_user/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof UserHomeImport
      parentRoute: typeof UserImport
    }
    '/_store/store/$slug/setting': {
      id: '/_store/store/$slug/setting'
      path: '/store/$slug/setting'
      fullPath: '/store/$slug/setting'
      preLoaderRoute: typeof StoreStoreSlugSettingImport
      parentRoute: typeof StoreImport
    }
    '/_store/store/$slug/': {
      id: '/_store/store/$slug/'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreStoreSlugIndexImport
      parentRoute: typeof StoreImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  SplitRoute: SplitRoute.addChildren({ SplitLoginRoute, SplitStoreRoute }),
  StoreRoute: StoreRoute.addChildren({
    StoreStoreSlugSettingRoute,
    StoreStoreSlugIndexRoute,
  }),
  UserRoute: UserRoute.addChildren({ UserHomeRoute }),
  AboutRoute,
  LogoutRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_split",
        "/_store",
        "/_user",
        "/about",
        "/logout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_split": {
      "filePath": "_split.tsx",
      "children": [
        "/_split/login",
        "/_split/store"
      ]
    },
    "/_store": {
      "filePath": "_store.tsx",
      "children": [
        "/_store/store/$slug/setting",
        "/_store/store/$slug/"
      ]
    },
    "/_user": {
      "filePath": "_user.tsx",
      "children": [
        "/_user/home"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/_split/login": {
      "filePath": "_split/login.tsx",
      "parent": "/_split"
    },
    "/_split/store": {
      "filePath": "_split/store.tsx",
      "parent": "/_split"
    },
    "/_user/home": {
      "filePath": "_user/home.tsx",
      "parent": "/_user"
    },
    "/_store/store/$slug/setting": {
      "filePath": "_store/store/$slug/setting.tsx",
      "parent": "/_store"
    },
    "/_store/store/$slug/": {
      "filePath": "_store/store/$slug/index.tsx",
      "parent": "/_store"
    }
  }
}
ROUTE_MANIFEST_END */
